/*
 * This source file was generated by the Gradle 'init' task
 */
package seleniumWebActions;

import org.openqa.selenium.WebElement;
import seleniumWebActions.browserInit.BrowserInit;
import seleniumWebActions.exceptions.WebDriverException;
import seleniumWebActions.exceptions.WebElementException;
import seleniumWebActions.locatorMethods.CountNoOfProducts;
import seleniumWebActions.locatorMethods.FindLocators;
import seleniumWebActions.locatorMethods.FindLocatorsUsingFindBy;
import seleniumWebActions.locatorMethods.ProductCountUsingFindElements;
import seleniumWebActions.webActions.ExploreWebElementMethod;
import seleniumWebActions.webActions.WebActionsofAddingItemToCart;
import seleniumWebActions.webActions.WebElementAction;
import seleniumWebActions.webDriverMethods.BrowserActions;
import seleniumWebActions.webDriverMethods.NavigationCommand;

public class App {

    public static void main(String[] args) throws InterruptedException {

        //Call BrowserInit
      /*  BrowserInit browserInit = new BrowserInit();
        browserInit.run();*/

        //Call WebElementAction
      /*  WebElementAction webElementAction=new WebElementAction();
        webElementAction.run();*/

        //Call ExploreWebElentMethod
   /*     ExploreWebElementMethod exploreWebElementMethod=new ExploreWebElementMethod();
        exploreWebElementMethod.run();*/

        //Call BrowserActions
    /*    BrowserActions browserActions = new BrowserActions();
        browserActions.run();*/

        //Call NavigationCommand
       /* NavigationCommand navigationCommand = new NavigationCommand();
        navigationCommand.run();*/

        //Call WebDriverException
       /* WebDriverException webDriverException=new WebDriverException();
        webDriverException.run();*/

        //Call WebElementClass
      /*  WebElementException webElementException=new WebElementException();
        webElementException.run();*/

        //CallnFindLocators
      /*  FindLocators findLocators=new FindLocators();
        findLocators.run();*/

        //Call FindLocatorsUsingFindBy
        /*FindLocatorsUsingFindBy findLocatorsUsingFindBy = new FindLocatorsUsingFindBy();
        findLocatorsUsingFindBy.run();
*/
        //Call CountNoOfProducts
       /* CountNoOfProducts countNoOfProducts = new CountNoOfProducts();
        countNoOfProducts.run();
*/
        //Call ProductCountUsingFindElements
        /*ProductCountUsingFindElements productCountUsingFindElements = new ProductCountUsingFindElements();
        productCountUsingFindElements.run();*/

        //Call WebActionsofAddingItemToCart
      /*  WebActionsofAddingItemToCart webActionsofAddingItemToCart = new WebActionsofAddingItemToCart();
        webActionsofAddingItemToCart.run();*/
    }
}
