/*
 * This source file was generated by the Gradle 'init' task
 */
package seleniumWebActions;

import org.openqa.selenium.WebElement;
import seleniumWebActions.browserInit.BrowserInit;
import seleniumWebActions.webActions.ExploreWebElementMethod;
import seleniumWebActions.webActions.WebElementAction;
import seleniumWebActions.webDriverMethods.BrowserActions;

public class App {

    public static void main(String[] args) throws InterruptedException {

        //Call BrowserInit
       /* BrowserInit browserInit = new BrowserInit();
        browserInit.run();*/

        //Call WebElementAction
      /*  WebElementAction webElementAction=new WebElementAction();
        webElementAction.run();*/

        //Call ExploreWebElentMethod
   /*     ExploreWebElementMethod exploreWebElementMethod=new ExploreWebElementMethod();
        exploreWebElementMethod.run();*/

        //Call BrowserActions
        BrowserActions browserActions = new BrowserActions();
        browserActions.run();
    }
}
